CREATE TABLE IF NOT EXISTS reset_password (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    NguoiDungId INT NOT NULL,
    Token VARCHAR(64) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayHetHan DATETIME NOT NULL,
    DaSuDung TINYINT(1) DEFAULT 0,
    FOREIGN KEY (NguoiDungId) REFERENCES nguoidung(Id)
);
